from elasticsearch import Elasticsearch
import ssl
import asyncio
import os
import re

print(os.getcwd())

# 创建一个Elasticsearch客户端

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "Q08La_9iZNc7RMCq7ZkJ"

# Create the client instance
es = Elasticsearch(
    "https://localhost:9200",
    ca_certs="src/data/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD),
)

# print(client.info())

# 判断索引是否存在，不存在则创建索引
if not es.indices.exists(index="sysu"):
    es.indices.create(index="sysu")

# 添加一个文档
doc = {
    "name": "中山大学",
    "description": """
    中山大学（英语：Sun Yat-sen University[注 4]，缩写：SYSU），简称中大[注 5]，是一所中国大陆的综合性研究型大学，位于广东省广州市、珠海市和深圳市，直属于中华人民共和国教育部，由教育部与广东省人民政府共建。

    中山大学前身为孙中山于1924年创立的国立广东大学，1926年为纪念孙中山改称国立中山大学。1927年国民政府模仿法国大学区制度，在全国建立四所中央级“中山大学”，该校改称为国立第一中山大学[注 6]，1928年复名为国立中山大学。1950年，去除“国立”称谓仅称中山大学。1952年全国院系调整中，原中山大学被拆分，众多院系被析出独立建校或并入他校，仅余文理院系与私立岭南大学、华南联合大学等院校的文理院系合并组建新的中山大学，并将校址迁至原岭南大学的校园康乐园。2001年，中山大学与曾经析出的中山医科大学合并，成为现在的中山大学。

    中山大学是中华人民共和国顶尖高校之一，现时属于“软科世界百强大学”，是“双一流A类”和原“985工程”、原“211工程”重点建设大学，是现时13所广东省高水平大学之一，在人文社会科学、医科和理科等学科门类实力雄厚，被誉为“华南第一学府”[2][3]。中山大学在2022年世界大学学术排名中，位列中国大陆第8名，世界第79名[4]；在2019年QS世界大学排名[5]、2019年泰晤士高等教育世界大学排名[6]和2020年U.S.NEWS世界大学排名[7]中，均位列中国大陆第8名，并分别位列世界第295名、301-350名与208名。

    中山大学现有三个校区、五个校园。其中，广州校区南校园位于广州市海珠区，别名“康乐园”，是中山大学的传统校区；广州校区北校园位于广州市越秀区，是原中山医科大学的校区；广州校区东校园位于广州市番禺区的广州大学城内；珠海校区位于珠海市香洲区唐家湾镇；深圳校区位于深圳市光明区猪公山。此外，中山大学也拥有规模庞大的医院体系，现有十家直属附属医院和多家非直属附属医院。
    """,
}
res = es.index(index="sysu", id=1, body=doc)
print(res["result"])  # 输出结果，如果存储成功，应该输出'created'或'updated'

query = {
    "query": {
        "bool": {
            "must": [
                # "filter": [  # 使用filter关键字，可以提高查询效率
                {"match": {"description": "中山大学"}},
                {"match": {"description": "校区"}},
                {"match": {"description": "年份"}},
            ]
        }
    },
    "highlight": {"fields": {"description": {}}},
}

res = es.search(index="sysu", body=query)

# 输出查询结果
for hit in res["hits"]["hits"]:
    print("Document ID: %s" % hit["_id"])
    print("Score: %s" % hit["_score"])
    # 删除所有的<em>和</em>标签
    cleaned_highlight = [
        re.sub("</?em>", "", highlight) for highlight in hit["highlight"]["description"]
    ]
    print("Highlight: %s" % cleaned_highlight)
